/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SessionId = IDL.Nat;
export const Time = IDL.Int;
export const Session = IDL.Record({
  'id' : SessionId,
  'startTime' : Time,
  'endTime' : Time,
  'name' : IDL.Text,
  'qrPayload' : IDL.Text,
});
export const AttendanceRecord = IDL.Record({
  'user' : IDL.Principal,
  'checkInTime' : Time,
  'sessionId' : SessionId,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIn' : IDL.Func([SessionId, IDL.Text], [], []),
  'createSession' : IDL.Func([IDL.Text, Time, Time], [Session], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getAttendanceForSession' : IDL.Func(
      [SessionId],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSession' : IDL.Func([SessionId], [IDL.Opt(Session)], ['query']),
  'getUserAttendance' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SessionId = IDL.Nat;
  const Time = IDL.Int;
  const Session = IDL.Record({
    'id' : SessionId,
    'startTime' : Time,
    'endTime' : Time,
    'name' : IDL.Text,
    'qrPayload' : IDL.Text,
  });
  const AttendanceRecord = IDL.Record({
    'user' : IDL.Principal,
    'checkInTime' : Time,
    'sessionId' : SessionId,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIn' : IDL.Func([SessionId, IDL.Text], [], []),
    'createSession' : IDL.Func([IDL.Text, Time, Time], [Session], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getAttendanceForSession' : IDL.Func(
        [SessionId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerAttendance' : IDL.Func(
        [],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSession' : IDL.Func([SessionId], [IDL.Opt(Session)], ['query']),
    'getUserAttendance' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };